//Auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_DETAIL = 'SET_CURRENT_USER_DETAIL';
export const CLEAR_CURRENT_USER_DETAIL = 'CLEAR_CURRENT_USER_DETAIL';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';

//Alerts
export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const REMOVE_ALERTS = 'REMOVE_ALERTS';

//Profile
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const LOAD_POSTS = 'LOAD_POSTS';
export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_MODAL_SHOW = 'SEARCH_MODAL_SHOW';
export const SEARCH_MODAL_HIDE = 'SEARCH_MODAL_HIDE';
